version: 2.0

references:

  container_config: &container_config
    docker:
      - image: circleci/node:11.11
    working_directory: ~/repo

  workspace_root: &workspace_root ~/repo

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - *restore_repo
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Install Azure CLI
          command: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Login to Azure CLI
          command: az login --service-principal --username $AZ_USERNAME --password $AZ_PASSWORD --tenant $AZ_TENANT --allow-no-subscriptions
      - run:
          name: Delete existing files
          command: az storage blob delete-batch --account-name $AZ_STORAGE_ACCOUNT_NAME --source \$web
      - run:
          name: Deploy the site
          command: az storage blob upload-batch --account-name $AZ_STORAGE_ACCOUNT_NAME --destination \$web --source ./public
      - run:
          name: Bust the cache
          command: az cdn endpoint purge --resource-group $AZ_CDN_RESOURCE_GROUP --profile-name $AZ_CDN_PROFILE_NAME --name $AZ_CDN_ENDPOINT_NAME --content-paths '/*' --no-wait

workflows:
  version: 2

  build_feature:
    jobs:
      - build:
          context: blockmedx-app-dev
          filters:
            branches:
              ignore:
                - develop
                - master

  build_and_deploy_dev:
    jobs:
      - build:
          context: blockmedx-app-dev
          filters:
            branches:
              only: circleci
      - deploy:
          context: blockmedx-app-dev
          requires:
            - build
          filters:
            branches:
              only: circleci

#  build_and_deploy_prod:
#    jobs:
#      - build:
#          context: blockmedx-app-prod
#          filters:
#            branches:
#              only: master
#      - deploy:
#          context: blockmedx-app-prod
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
